#! /bin/bash

if [ -z $NETKIT_HOME ] ; then
	export NETKIT_HOME=/home/sal/netkit
	export PATH=$PATH:$NETKIT_HOME/bin
fi

DIR=$1
PARALLEL=$2

if $PARALLEL ; then
	lstart -p -d $DIR
else
	lstart -d $DIR
fi

exit;
