near(1,2).
near(2,3).
near(3,4).
near(4,5).
near(5,6).
near(6,7).
near(7,8).

object(ciccio).
object(smoking).
object(table).
object(flowers).
object(dinner).

room(1..5).

position(1..8).

direction(left).
direction(right).
direction(up).
direction(down).

topRoom(1,2).
topRoom(2,3).
topRoom(3,4).
topRoom(4,5).
bottomRoom(L,H) :- topRoom(H,L).

doorUp(S,P) :- doorDown(S1,P), S=S1+1.
doorDown(1,3).
doorDown(2,3).
doorDown(3,1).
doorDown(4,8).
