#! /bin/bash

if [ -z $NETKIT_HOME ] ; then
	export NETKIT_HOME=/home/sal/netkit
	export PATH=$PATH:$NETKIT_HOME/bin
fi

DIR=$1

CRASH=$2

if $CRASH ; then
	lcrash -d $DIR
else
	lhalt -d $DIR
fi

exit;